on:
  push:
    paths-ignore:
      - 'issue-reports/**'
  pull_request:
    paths-ignore:
      - 'issue-reports/**'
name: lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Setup dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint
